apiVersion: v1
kind: Secret
metadata:
  name: {{ include "blotto.fullname" . }}-db
  labels:
    {{- include "blotto.labels" . | nindent 4 }}
type: Opaque
data:
  password: {{ .Values.database.password | b64enc | quote }}
