apiVersion: v1
kind: Secret
metadata:
  name: {{ include "outplaylabs-arena.fullname" . }}-db
  labels:
    {{- include "outplaylabs-arena.labels" . | nindent 4 }}
type: Opaque
data:
  password: {{ .Values.database.password | b64enc | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "outplaylabs-arena.fullname" . }}-oauth
  labels:
    {{- include "outplaylabs-arena.labels" . | nindent 4 }}
type: Opaque
data:
  callback-base-url: {{ .Values.oauth.callbackBaseUrl | b64enc | quote }}
  github-client-id: {{ .Values.oauth.githubClientId | b64enc | quote }}
  github-client-secret: {{ .Values.oauth.githubClientSecret | b64enc | quote }}
  google-client-id: {{ .Values.oauth.googleClientId | b64enc | quote }}
  google-client-secret: {{ .Values.oauth.googleClientSecret | b64enc | quote }}
  jwt-secret: {{ .Values.oauth.jwtSecret | b64enc | quote }}
