{{- if .Values.traefik.enabled }}
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: {{ include "arena.fullname" . }}-docs
  labels:
    {{- include "arena.labels" . | nindent 4 }}
    app.kubernetes.io/component: docs
spec:
  entryPoints:
    - web
    - websecure
  routes:
    - kind: Rule
      match: Host(`docs.{{ .Values.traefik.host }}`)
      services:
        - kind: Service
          name: {{ include "arena.fullname" . }}-docs
          port: 80
{{- if or .Values.traefik.certResolver .Values.traefik.tlsSecret }}
  tls:
  {{- if .Values.traefik.certResolver }}
    certResolver: {{ .Values.traefik.certResolver }}
  {{- else }}
    secretName: {{ .Values.traefik.tlsSecret | default (printf "%s-tls" (include "arena.fullname" .)) }}
  {{- end }}
{{- end }}
{{- end }}
