codecov:
  require_ci_to_pass: true
  status:
    project:
      default:
        target: 90%
        threshold: 2%
    patch:
      default:
        target: 90%
  ignore:
    - "games/games/_template/**"
    - "scripts/**"
