apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "nasharena.fullname" . }}-backend
  labels:
    {{- include "nasharena.labels" . | nindent 4 }}
    app.kubernetes.io/component: backend
