{{- if .Values.backend.podDisruptionBudget.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "outplaylabs-arena.fullname" . }}-backend
  labels:
    {{- include "outplaylabs-arena.labels" . | nindent 4 }}
    app.kubernetes.io/component: backend
spec:
  minAvailable: {{ .Values.backend.podDisruptionBudget.minAvailable }}
  selector:
    matchLabels:
      {{- include "outplaylabs-arena.backend.selectorLabels" . | nindent 6 }}
{{- end }}
