apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "outplaylabs-arena.fullname" . }}-backend
  labels:
    {{- include "outplaylabs-arena.labels" . | nindent 4 }}
    app.kubernetes.io/component: backend
