apiVersion: v1
kind: Service
metadata:
  name: {{ include "outplaylabs-arena.fullname" . }}-backend
  labels:
    {{- include "outplaylabs-arena.labels" . | nindent 4 }}
    app.kubernetes.io/component: backend
spec:
  type: ClusterIP
  ports:
    - port: 8000
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "outplaylabs-arena.backend.selectorLabels" . | nindent 4 }}
