apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "blotto.fullname" . }}-frontend
  labels:
    {{- include "blotto.labels" . | nindent 4 }}
    app.kubernetes.io/component: frontend
data:
  index.html: |
{{ .Files.Get "static/index.html" | indent 4 }}
  app.js: |
{{ .Files.Get "static/app.js" | indent 4 }}
  style.css: |
{{ .Files.Get "static/style.css" | indent 4 }}
