apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: {{ include "outplaylabs-arena.fullname" . }}-ratelimit
  labels:
    {{- include "outplaylabs-arena.labels" . | nindent 4 }}
spec:
  rateLimit:
    average: {{ .Values.traefik.middleware.rateLimit.average }}
    burst: {{ .Values.traefik.middleware.rateLimit.burst }}
