"""add_public_url_to_mcp_instances

Revision ID: 0f0e87320c1f
Revises: d7e8f9g0h1
Create Date: 2026-06-12 22:23:45.430139

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0f0e87320c1f'
down_revision: Union[str, Sequence[str], None] = 'd7e8f9g0h1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mcp_instances', sa.Column('public_url', sa.String(length=512), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('mcp_instances', 'public_url')
    # ### end Alembic commands ###
