apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: {{ include "arena.fullname" . }}
  labels:
    {{- include "arena.labels" . | nindent 4 }}
spec:
  entryPoints:
    - web
    - websecure
  routes:
    - kind: Rule
      match: Host(`{{ .Values.traefik.host }}`)
      services:
        - kind: Service
          name: {{ include "arena.fullname" . }}-backend
          port: 8000
    - kind: Rule
      match: Host(`api.{{ .Values.traefik.host }}`)
      middlewares:
        - name: {{ include "arena.fullname" . }}-ratelimit
      services:
        - kind: Service
          name: {{ include "arena.fullname" . }}-backend
          port: 8000
    - kind: Rule
      match: HostRegexp(`^.+$`)
      services:
        - kind: Service
          name: {{ include "arena.fullname" . }}-backend
          port: 8000
{{- if or .Values.traefik.certResolver .Values.traefik.tlsSecret }}
  tls:
  {{- if .Values.traefik.certResolver }}
    certResolver: {{ .Values.traefik.certResolver }}
  {{- else }}
    secretName: {{ .Values.traefik.tlsSecret | default (printf "%s-tls" (include "arena.fullname" .)) }}
  {{- end }}
{{- end }}
